#spring:
#  application:
#    name: micro-weather-report-server-eureka-feign-gateway
#  thymeleaf:
#    cache: false # 热部署静态文件
#server:
#  port: 18084
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka/
#  instance:
#    prefer-ip-address: true
#fegin:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      feignName:
#        connectTimeout: 5000
#        readTimeout: 5000
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream