spring:
  application:
    name: micro-weather-eureka-client-feign
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true

fegin:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
