spring:
  application:
    name: micro-weather-eureka-client
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#
##      http://admin:123456@${eureka.instance.hostname}:${server.port}/eureka/
