spring:
  application:
    name: micro-weather-data-server-eureka
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true